package de.dirkgasser.brauen;

import static de.dirkgasser.brauen.BrewComputerMain.brewRecipe;
import static de.dirkgasser.brauen.BrewComputerMain.brewframe;
import static de.dirkgasser.brauen.BrewComputerMain.testFrame;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JMenu;

/**
 * JFrame for editing and selection a brew recipe <br>
 * Designed with NetBeans editor, therefor some components are placeholder <br>
 * Panel jpRecipeNames: Replaced by JPRecipeNames <br>
 * Panel jpBrewProcess: Replaced by JPRecipeProcess <br>
 * Panel jpIngredients: Replaced by JPIngredients
 * @author Dirk Gasser
 * @version 1.0
 */
public class RecipeFrame extends javax.swing.JFrame {
    double width = 800;
    double height = 480;
    Dimension dim;
    private javax.swing.JTextField jtBezeichung1;
    private javax.swing.JTextField jtSchritt1;
    private javax.swing.JTextField jtBezeichung2;
    private javax.swing.JTextField jtSchritt2;
/**
* Creates new form RecipeFrame <br>
* All information is taken from global variables <br>
*/
    public RecipeFrame() {
/*
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        width = screenSize.getWidth();
        height = screenSize.getHeight();
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
*/
       initComponents();
       dim = new Dimension();
       dim.setSize(width, height);
       this.setMinimumSize(dim);
       this.setPreferredSize(dim);
       
       
       jspRecipeNames.remove(jpRecipeNames);
       jspRecipeNames.setViewportView(new JPRecipeNames(true));
       jtRecipeName.setText(brewRecipe.getRecipeName());
       
       jspBrewProcess.remove(jpBrewProcess);
       jspBrewProcess.setViewportView(new JPRecipeProcess(brewRecipe));
       
       jspIngredients.remove(jpIngredients);
       jspIngredients.setViewportView(new JPIngredients(brewRecipe));
       
       pack();
       
    }
    
/**
 * Read actual BrewRecipe from global variable an shwon in frame
 */
    public void readRecipe() {
       jtRecipeName.setText(brewRecipe.getRecipeName());
       
       jspBrewProcess.remove(jpBrewProcess);
       jspBrewProcess.setViewportView(new JPRecipeProcess(brewRecipe));
       
       jspIngredients.remove(jpIngredients);
       jspIngredients.setViewportView(new JPIngredients(brewRecipe));
       
       this.setMinimumSize(dim);
       this.setPreferredSize(dim);
       
       pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jspRecipeNames = new javax.swing.JScrollPane();
        jpRecipeNames = new javax.swing.JPanel();
        jbRecipeName = new javax.swing.JButton();
        jbRecipeName1 = new javax.swing.JButton();
        jbRecipeName2 = new javax.swing.JButton();
        jlRecipe = new javax.swing.JLabel();
        jlSchritt = new javax.swing.JLabel();
        jlBezeichnung = new javax.swing.JLabel();
        jspBrewProcess = new javax.swing.JScrollPane();
        jpBrewProcess = new javax.swing.JPanel();
        jtSchritt = new javax.swing.JTextField();
        jtBezeichnung = new javax.swing.JTextField();
        jcbStart = new javax.swing.JComboBox<>();
        jtDauer = new javax.swing.JTextField();
        lbMin = new javax.swing.JLabel();
        jtTemperatur = new javax.swing.JTextField();
        lbCelsius = new javax.swing.JLabel();
        bDeletebs = new java.awt.Button();
        bNewStep = new java.awt.Button();
        jtSchritt3 = new javax.swing.JTextField();
        jtBezeichnung1 = new javax.swing.JTextField();
        jcbStart1 = new javax.swing.JComboBox<>();
        jtDauer1 = new javax.swing.JTextField();
        lbMin1 = new javax.swing.JLabel();
        jtTemperatur1 = new javax.swing.JTextField();
        lbCelsius1 = new javax.swing.JLabel();
        bDeletebs1 = new java.awt.Button();
        bNewStep1 = new java.awt.Button();
        jtSchritt4 = new javax.swing.JTextField();
        jtDauer2 = new javax.swing.JTextField();
        jtBezeichnung2 = new javax.swing.JTextField();
        jtTemperatur2 = new javax.swing.JTextField();
        lbCelsius2 = new javax.swing.JLabel();
        lbMin2 = new javax.swing.JLabel();
        bNewStep2 = new java.awt.Button();
        jcbStart2 = new javax.swing.JComboBox<>();
        bDeletebs2 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jspIngredients = new javax.swing.JScrollPane();
        jpIngredients = new javax.swing.JPanel();
        jcIngredType = new javax.swing.JComboBox<>();
        jtIngredDescription = new javax.swing.JTextField();
        jtAmount = new javax.swing.JTextField();
        jtUnit = new javax.swing.JTextField();
        jcProperty = new javax.swing.JComboBox<>();
        jcStepconnect = new javax.swing.JComboBox<>();
        jtPropertyValue = new javax.swing.JTextField();
        jbDeleteIngred = new javax.swing.JButton();
        jcIngredType1 = new javax.swing.JComboBox<>();
        jtIngredDescription1 = new javax.swing.JTextField();
        jtAmount1 = new javax.swing.JTextField();
        jtUnit1 = new javax.swing.JTextField();
        jcProperty1 = new javax.swing.JComboBox<>();
        jtPropertyValue1 = new javax.swing.JTextField();
        jcStepconnect1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jtIngredDescription2 = new javax.swing.JTextField();
        jtAmount2 = new javax.swing.JTextField();
        jtPropertyValue2 = new javax.swing.JTextField();
        jtUnit2 = new javax.swing.JTextField();
        jcIngredType2 = new javax.swing.JComboBox<>();
        jcProperty2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jcStepconnect2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtRecipeName = new javax.swing.JTextField();
        jbSpeichern = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmTest = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jspRecipeNames.setMinimumSize(new java.awt.Dimension(23, 400));

        jbRecipeName.setText("jButton1");

        jbRecipeName1.setText("jButton1");

        jbRecipeName2.setText("jButton1");

        javax.swing.GroupLayout jpRecipeNamesLayout = new javax.swing.GroupLayout(jpRecipeNames);
        jpRecipeNames.setLayout(jpRecipeNamesLayout);
        jpRecipeNamesLayout.setHorizontalGroup(
            jpRecipeNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecipeNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRecipeNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRecipeName)
                    .addComponent(jbRecipeName1)
                    .addComponent(jbRecipeName2))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jpRecipeNamesLayout.setVerticalGroup(
            jpRecipeNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRecipeNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbRecipeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRecipeName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRecipeName2)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        jspRecipeNames.setViewportView(jpRecipeNames);

        jlRecipe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlRecipe.setText("Rezepte");

        jlSchritt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlSchritt.setText("Schritt");

        jlBezeichnung.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlBezeichnung.setText("Bezeichnung");

        jspBrewProcess.setMinimumSize(new java.awt.Dimension(100, 200));
        jspBrewProcess.setPreferredSize(new java.awt.Dimension(650, 120));

        jpBrewProcess.setPreferredSize(new java.awt.Dimension(600, 120));

        jtSchritt.setEditable(false);

        jtBezeichnung.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtBezeichnung.setPreferredSize(new java.awt.Dimension(4, 25));

        jcbStart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manuell", "automatisch" }));

        lbMin.setText("min.");

        lbCelsius.setText("°C");

        bDeletebs.setActionCommand("delete");
        bDeletebs.setLabel("löschen");
        bDeletebs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletebsActionPerformed(evt);
            }
        });

        bNewStep.setLabel("neu");
        bNewStep.setName(""); // NOI18N

        jtSchritt3.setEditable(false);

        jtBezeichnung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBezeichnung1ActionPerformed(evt);
            }
        });

        jcbStart1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manuell", "automatisch" }));

        lbMin1.setText("min.");

        lbCelsius1.setText("°C");

        bDeletebs1.setActionCommand("delete");
        bDeletebs1.setLabel("löschen");
        bDeletebs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletebs1ActionPerformed(evt);
            }
        });

        bNewStep1.setLabel("neu");
        bNewStep1.setName(""); // NOI18N

        jtSchritt4.setEditable(false);

        jtBezeichnung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBezeichnung2ActionPerformed(evt);
            }
        });

        lbCelsius2.setText("°C");

        lbMin2.setText("min.");

        bNewStep2.setLabel("neu");
        bNewStep2.setName(""); // NOI18N

        jcbStart2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manuell", "automatisch" }));

        bDeletebs2.setActionCommand("delete");
        bDeletebs2.setLabel("löschen");
        bDeletebs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletebs2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBrewProcessLayout = new javax.swing.GroupLayout(jpBrewProcess);
        jpBrewProcess.setLayout(jpBrewProcessLayout);
        jpBrewProcessLayout.setHorizontalGroup(
            jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBrewProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBrewProcessLayout.createSequentialGroup()
                        .addComponent(jtSchritt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtDauer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMin)
                        .addGap(32, 32, 32)
                        .addComponent(jtTemperatur, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCelsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDeletebs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNewStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBrewProcessLayout.createSequentialGroup()
                        .addComponent(jtSchritt3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtBezeichnung1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbStart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtDauer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMin1)
                        .addGap(32, 32, 32)
                        .addComponent(jtTemperatur1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCelsius1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDeletebs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNewStep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBrewProcessLayout.createSequentialGroup()
                        .addComponent(jtSchritt4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtBezeichnung2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbStart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtDauer2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMin2)
                        .addGap(32, 32, 32)
                        .addComponent(jtTemperatur2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCelsius2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDeletebs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNewStep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBrewProcessLayout.setVerticalGroup(
            jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBrewProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bNewStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeletebs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtSchritt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtDauer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMin)
                        .addComponent(jtTemperatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCelsius)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bNewStep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeletebs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtSchritt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtBezeichnung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbStart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtDauer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMin1)
                        .addComponent(jtTemperatur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCelsius1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bNewStep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeletebs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBrewProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtSchritt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtBezeichnung2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbStart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtDauer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMin2)
                        .addComponent(jtTemperatur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCelsius2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        bDeletebs.getAccessibleContext().setAccessibleName("delete");

        jspBrewProcess.setViewportView(jpBrewProcess);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Start");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Dauer");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Temperatur");

        jspIngredients.setMaximumSize(new java.awt.Dimension(640, 180));
        jspIngredients.setMinimumSize(new java.awt.Dimension(640, 180));
        jspIngredients.setPreferredSize(new java.awt.Dimension(640, 180));

        jcIngredType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wasser", "Malz", "Hopfen", "Hefe" }));
        jcIngredType.setName("cbIngredType"); // NOI18N

        jcProperty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "n/a", "EBC", "Alpha %" }));

        jcStepconnect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbDeleteIngred.setText("löschen");

        jcIngredType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wasser", "Malz", "Hopfen", "Hefe" }));
        jcIngredType1.setName("cbIngredType"); // NOI18N

        jcProperty1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "n/a", "EBC", "Alpha %" }));

        jcStepconnect1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("löschen");

        jcIngredType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wasser", "Malz", "Hopfen", "Hefe" }));
        jcIngredType2.setName("cbIngredType"); // NOI18N

        jcProperty2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "n/a", "EBC", "Alpha %" }));

        jButton3.setText("löschen");

        jcStepconnect2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpIngredientsLayout = new javax.swing.GroupLayout(jpIngredients);
        jpIngredients.setLayout(jpIngredientsLayout);
        jpIngredientsLayout.setHorizontalGroup(
            jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngredientsLayout.createSequentialGroup()
                        .addComponent(jcIngredType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtIngredDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPropertyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcStepconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeleteIngred))
                    .addGroup(jpIngredientsLayout.createSequentialGroup()
                        .addComponent(jcIngredType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtIngredDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcStepconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jpIngredientsLayout.createSequentialGroup()
                        .addComponent(jcIngredType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtIngredDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcProperty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPropertyValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcStepconnect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpIngredientsLayout.setVerticalGroup(
            jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngredientsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcIngredType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIngredDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcStepconnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPropertyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeleteIngred))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcIngredType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIngredDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcStepconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPropertyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpIngredientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcIngredType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtIngredDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUnit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProperty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcStepconnect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPropertyValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jspIngredients.setViewportView(jpIngredients);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Zutat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Bezeichnung");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Menge");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Eigenschaft");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Zugabe in Schritt");

        jtRecipeName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtRecipeName.setPreferredSize(new java.awt.Dimension(4, 30));
        jtRecipeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtRecipeNameKeyReleased(evt);
            }
        });

        jbSpeichern.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSpeichern.setText("Speichner");
        jbSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSpeichernActionPerformed(evt);
            }
        });

        jMenuBar1.setFocusable(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(169, 40));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setText("Rezept");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Brauen");
        jMenu2.setDelay(20);
        jMenu2.setFocusPainted(true);
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jMenu2.setName(""); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jMenu2, org.jdesktop.beansbinding.ELProperty.create("${action}"), jMenu2, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jmTest.setText("Test");
        jmTest.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jmTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTestMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmTest);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jspRecipeNames, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jlSchritt)
                        .addGap(18, 18, 18)
                        .addComponent(jlBezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel5)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel6)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel7)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jspBrewProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jspIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addComponent(jtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSpeichern)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSpeichern, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRecipe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSchritt)
                            .addComponent(jlBezeichnung)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspBrewProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addComponent(jspRecipeNames, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        FullScreen.fullScreen(brewframe, false);
        brewframe.setVisible(true);
        brewframe.requestFocus();
        brewframe.refreshRecipe();
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void bDeletebsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletebsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeletebsActionPerformed

    private void jtBezeichnung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBezeichnung1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBezeichnung1ActionPerformed

    private void bDeletebs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletebs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeletebs1ActionPerformed

    private void jtBezeichnung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBezeichnung2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBezeichnung2ActionPerformed

    private void bDeletebs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletebs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeletebs2ActionPerformed

    private void jbSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSpeichernActionPerformed
        brewRecipe.writeBrewRecipe();
        jspRecipeNames.remove(jpRecipeNames);
        jspRecipeNames.setViewportView(new JPRecipeNames(false));     
    }//GEN-LAST:event_jbSpeichernActionPerformed

    private void jtRecipeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRecipeNameKeyReleased
        if(jtRecipeName.getText().length() < 30) {
            brewRecipe.setRecipeName(jtRecipeName.getText());
        } else {
            jtRecipeName.setText(jtRecipeName.getText().substring(0, 15));
        }    
    }//GEN-LAST:event_jtRecipeNameKeyReleased

    private void jmTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTestMouseClicked
        // TODO add your handling code here:
        FullScreen.fullScreen(testFrame, false);
        testFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmTestMouseClicked

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        FullScreen.fullScreen(brewframe, false);
        brewframe.setVisible(true);
        brewframe.requestFocus();
        brewframe.refreshRecipe();
    }//GEN-LAST:event_jMenu2MousePressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bDeletebs;
    private java.awt.Button bDeletebs1;
    private java.awt.Button bDeletebs2;
    private java.awt.Button bNewStep;
    private java.awt.Button bNewStep1;
    private java.awt.Button bNewStep2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbDeleteIngred;
    private javax.swing.JButton jbRecipeName;
    private javax.swing.JButton jbRecipeName1;
    private javax.swing.JButton jbRecipeName2;
    private javax.swing.JButton jbSpeichern;
    private javax.swing.JComboBox<String> jcIngredType;
    private javax.swing.JComboBox<String> jcIngredType1;
    private javax.swing.JComboBox<String> jcIngredType2;
    private javax.swing.JComboBox<String> jcProperty;
    private javax.swing.JComboBox<String> jcProperty1;
    private javax.swing.JComboBox<String> jcProperty2;
    private javax.swing.JComboBox<String> jcStepconnect;
    private javax.swing.JComboBox<String> jcStepconnect1;
    private javax.swing.JComboBox<String> jcStepconnect2;
    private javax.swing.JComboBox<String> jcbStart;
    private javax.swing.JComboBox<String> jcbStart1;
    private javax.swing.JComboBox<String> jcbStart2;
    private javax.swing.JLabel jlBezeichnung;
    private javax.swing.JLabel jlRecipe;
    private javax.swing.JLabel jlSchritt;
    private javax.swing.JMenu jmTest;
    private javax.swing.JPanel jpBrewProcess;
    private javax.swing.JPanel jpIngredients;
    private javax.swing.JPanel jpRecipeNames;
    private javax.swing.JScrollPane jspBrewProcess;
    private javax.swing.JScrollPane jspIngredients;
    private javax.swing.JScrollPane jspRecipeNames;
    private javax.swing.JTextField jtAmount;
    private javax.swing.JTextField jtAmount1;
    private javax.swing.JTextField jtAmount2;
    private javax.swing.JTextField jtBezeichnung;
    private javax.swing.JTextField jtBezeichnung1;
    private javax.swing.JTextField jtBezeichnung2;
    private javax.swing.JTextField jtDauer;
    private javax.swing.JTextField jtDauer1;
    private javax.swing.JTextField jtDauer2;
    private javax.swing.JTextField jtIngredDescription;
    private javax.swing.JTextField jtIngredDescription1;
    private javax.swing.JTextField jtIngredDescription2;
    private javax.swing.JTextField jtPropertyValue;
    private javax.swing.JTextField jtPropertyValue1;
    private javax.swing.JTextField jtPropertyValue2;
    private javax.swing.JTextField jtRecipeName;
    private javax.swing.JTextField jtSchritt;
    private javax.swing.JTextField jtSchritt3;
    private javax.swing.JTextField jtSchritt4;
    private javax.swing.JTextField jtTemperatur;
    private javax.swing.JTextField jtTemperatur1;
    private javax.swing.JTextField jtTemperatur2;
    private javax.swing.JTextField jtUnit;
    private javax.swing.JTextField jtUnit1;
    private javax.swing.JTextField jtUnit2;
    private javax.swing.JLabel lbCelsius;
    private javax.swing.JLabel lbCelsius1;
    private javax.swing.JLabel lbCelsius2;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbMin1;
    private javax.swing.JLabel lbMin2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
